---
- name: This playbook install apache on rhel and ubuntu
  hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == 'RedHat'
    notify: copy index.html
    tags: install_apache

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
    when: ansible_os_family == 'RedHat'
    tags: start_apache
    ignore_errors: yes

  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: ansible_os_family == 'RedHat'

  - name: Enable firewalld
    service:
      name: firewalld
      state: started
    when: ansible_os_family == 'RedHat'

  - name: Apache2 Installation for Debian Base OS
    apt:
      name: apache2
      state: present
    when: ansible_os_family == 'Debian'

  - name: Start Apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == 'Debian'
  
  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666


