---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks:
  - name: install multiple packages
    yum: 
      name: '{{ item }}'
      state: installed
    with_items:
       - git
       - make
       - gcc
       - wget
       - telnet
       - gzip
