---
- name: This playbook uninstall httpd
  hosts: webservers
  become: true
  tasks:
  - name: Disable service to start on boot up
    service:
      name: httpd
      state: stopped
  - name: Uninstall the httpd
    yum:
      name: httpd
      autoremove: yes
      state: absent
  - name: Delete firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: disabled
